use ZER@_DENGUE
GO

CREATE TABLE Cadastro ( id INT IDENTITY(1,1) NOT NULL, 
					    email VARCHAR(50) NOT NULL,
						senha VARCHAR(12) NOT NULL,
PRIMARY KEY CLUSTERED (id) )
GO

CREATE TABLE USUARIO ( ID INT IDENTITY (1,1) NOT NULL,
					   nome VARCHAR (50) NOT NULL,
					   CPF CHAR (11) NOT NULL,
					   RG VARCHAR (15) NOT NULL,
					   email VARCHAR (50) NOT NULL,
					   contato VARCHAR (11),
					   estado CHAR (2) NOT NULL,
					   cidade VARCHAR (25) NOT NULL,
					   BAIRRO VARCHAR (50) NOT NULL,
					   RUA VARCHAR (50) NOT NULL,
					   FK_CADASTRO_ID INT NOT NULL,
PRIMARY KEY CLUSTERED (ID),
CONSTRAINT [FK_USUARIO_Cadastro_FK_CADASTRO_ID] FOREIGN KEY (FK_CADASTRO_ID) REFERENCES Cadastro (id))
GO

--denuncia
CREATE TABLE DENUNCIA ( ID INT IDENTITY (1,1) NOT NULL,
						ENDERECO VARCHAR (50) NOT NULL,
						BARIRRO VARCHAR (50) NOT NULL,
						DESCRICAO TEXT,
						FK_USUARIO_ID INT NOT NULL,
PRIMARY KEY CLUSTERED (ID),
CONSTRAINT [FK_DENUNCIA_USUARIO_FK_USUARIO_ID] FOREIGN KEY (FK_USUARIO_ID) REFERENCES USUARIO (ID))
GO

--imagem
CREATE TABLE IMAGEM (ID INT IDENTITY (1,1) NOT NULL,
					IMAGEM IMAGE NOT NULL,
					FK_DENUNCIA_id int not null,
PRIMARY KEY CLUSTERED (ID),
CONSTRAINT [FK_IMAGEM_DENUNCIA_FK_DENUNCIA_ID] FOREIGN KEY (FK_DENUNCIA_ID) REFERENCES DENUNCIA (ID))
GO

--funcionario
CREATE TABLE FUNCIONARIO (ID INT IDENTITY (1,1) NOT NULL,
					FK_USUARIO_id int not null,
PRIMARY KEY CLUSTERED (ID),
CONSTRAINT [FK_FUNCIONARIO_USUARIO_FK_USUARIO_ID] FOREIGN KEY (FK_USUARIO_id) REFERENCES USUARIO (ID))
GO

--relatorio
CREATE TABLE relatorio (ID INT IDENTITY (1,1) NOT NULL,
						RELATORIO TEXT NOT NULL,
						CONCLUSAO VARCHAR NOT NULL,
						FK_DENUNCIA_ID INT NOT NULL,
						FK_FUNCIONARIO_ID INT NOT NULL,
CONSTRAINT [FK_RELATORIO_DENUNCIA_FK_DENUNCIA_ID] FOREIGN KEY (FK_DENUNCIA_ID) REFERENCES DENUNCIA (ID),
CONSTRAINT [FK_RELATORIO_FUNCIONARIO_FK_FUNCIONARIO_ID] FOREIGN KEY (FK_FUNCIONARIO_ID) REFERENCES FUNCIONARIO (ID))
GO



/*
TIPO variáveis INTEIRO
smallint - -254 ATÉ 254 
TINYINT - -99 A 99
int = -9.9999.999 A 9.9999.999
BIGINT -9999999999999  a 9999999999999

TIPO variáveis strings
varchar (50) --NOME
char (2) UF 
text

IDENTITY(1,1) CONTROLE INTERNO DE AUTOINCREMENTO 
*/
